name: Relatar um Problema
description: Use este formulário para reportar um bug ou comportamento inesperado.
title: "[BUG] Descreva brevemente o problema"

body:
  - type: markdown
    attributes:
      value: |
        Obrigado por abrir uma issue!  
        Preencha as informações abaixo com o máximo de detalhes possível.

  # - type: input
  #   id: resumo
  #   attributes:
  #     label: Resumo do problema
  #     description: Dê um título curto e claro para o problema.
  #     placeholder: Exemplo: "Erro ao salvar formulário de cadastro"
  #   validations:
  #     required: true

  - type: textarea
    id: descricao
    attributes:
      label: Descrição detalhada
      description: Explique o que aconteceu e o que você esperava que acontecesse.
      placeholder: Descreva o comportamento observado e o comportamento esperado.
    validations:
      required: true

  - type: textarea
    id: passos
    attributes:
      label: Passos para reproduzir
      description: Liste os passos para reproduzir o problema.
      placeholder: |
        1. Vá para '...'
        2. Clique em '...'
        3. Veja o erro

  - type: dropdown
    id: prioridade
    attributes:
      label: Prioridade
      description: Qual a urgência deste problema?
      options:
        - Alta
        - Média
        - Baixa
    validations:
      required: true
